import {v4 as uuidv4} from 'uuid';

function collectionOfMusic(){
    return[
        {
            name: "Ae Dil Hai Mushkil",
            singer: "Pritam , Amit Mishra",
            cover: "https://c.saavncdn.com/257/Ae-Dil-Hai-Mushkil-Hindi-2016-500x500.jpg",
            audio: "https://mp3.chillhop.com/serve.php/?mp3=55163",
            color: ["#D19F85", "#1E588A"],
            id:uuidv4(),
            active:true,
        },
        {
            name: "O Bedardeya",
            singer: "Arijit Singh ",
            cover: "https://c.saavncdn.com/576/O-Bedardeya-From-Tu-Jhoothi-Main-Makkaar-Hindi-2023-20230303194422-500x500.jpg",
            color: ["#417468", "#874B4F"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Toofan",
            singer: "Sandesh Datta Naik ft. Laxman Datta Naik, Brijesh Shandilya ",
            cover: "https://c.saavncdn.com/592/KGF-Chapter-2-Hindi-2022-20220415034804-500x500.jpg",
            audio: "https://mp3.chillhop.com/serve.php/?mp3=55163",
            color: ["#D0F3FA", "#6C531E"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Jugnu ",
            singer: "Badshah",
            cover: "https://c.saavncdn.com/artists/Badshah_004_20191118143638_500x500.jpg",
            audio: "https://mp3.chillhop.com/serve.php/?mp3=55163",
            color: ["#312622", "#FBBF79"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Tere Sang Yaara",
            singer: "Atif Aslam",
            cover: "https://c.saavncdn.com/221/Rustom-Hindi-2018-20191029174008-500x500.jpg",
            audio: "https://mp3.chillhop.com/serve.php/?mp3=55163",
            color: ["#CCBB81", "#282637"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Zaalima ",
            singer: "Arijit Singh , Harshdeep kaur",
            cover: "https://c.saavncdn.com/334/Raees-Hindi-2016-20200430093124-500x500.jpg",
            audio: "https://mp3.chillhop.com/serve.php/?mp3=55163",
            color: ["#2C3831", "#CBC386"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Nashe Si Chadh Gayi ",
            singer: "Vishal & Shekhar",
            cover: "https://c.saavncdn.com/256/Befikre-Hindi-2016-20190329150318-500x500.jpg",
            audio: "https://mp3.chillhop.com/serve.php/?mp3=55163",
            color: ["#E85D99", "#F7A9FD"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Sanam Re ",
            singer: "Arijit Singh , Mithoon ",
            cover: "https://c.saavncdn.com/829/Sanam-Re-Hindi-2015-500x500.jpg",
            audio: "https://mp3.chillhop.com/serve.php/?mp3=55163",
            color: ["#CE8873", "#4C56CA"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Main Tera Boyfriend",
            singer: "Arijit Singh , Neha kakkar ",
            cover: "https://c.saavncdn.com/023/Raabta-Hindi-2017-500x500.jpg",
            audio: "https://mp3.chillhop.com/serve.php/?mp3=55163",
            color: ["#EEE9D3", "#050505"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Raataan Lambiyan ",
            singer: "Tanishk Bagchi, Jubin Nautiyal, Asees Kaur ft. Jubin Nautiyal",
            cover: "https://c.saavncdn.com/238/Shershaah-Original-Motion-Picture-Soundtrack--Hindi-2021-20210815181610-500x500.jpg",
            audio: "https://mp3.chillhop.com/serve.php/?mp3=55163",
            color: ["#8CA3AB", "#DED9DF"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Pal Pal Dil Ke Pass ",
            singer: "Arijit SIngh Parampara Tandon",
            cover: "https://c.saavncdn.com/328/Pal-Pal-Dil-Ke-Paas-Hindi-2019-20200420150444-500x500.jpg",
            audio: "https://mp3.chillhop.com/serve.php/?mp3=55163",
            color: ["#080308", "#E4F142"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Agar Tum Saath Ho",
            singer: "Alka Yagnik , Arijit Singh ",
            cover: "https://c.saavncdn.com/994/Tamasha-Hindi-2015-500x500.jpg",
            audio: "https://mp3.chillhop.com/serve.php/?mp3=55163",
            color: ["#DA6E30", "#DF7B5D"],
            id: uuidv4(),
            active: false,
        },
    ];
}

export default collectionOfMusic;